### ISSUE TITLE
GTF Chr name and genome chr name

### ISSUE THREAD

**Issue by zhypan** [Ensembl/ensembl-biomart#125]
Hi,

    I download the Homo_sapiens.GRCh38.100.gtf from Ensemble, and download genome from UCSC.  
http://hgdownload.soe.ucsc.edu/goldenPath/hg38/bigZips/

I find a serious problem, the Chr name unmatches for these two.
The ensemble has a scaffold call KI270713.1 , but can not find in UCSC hg38.chrom.sizes file?
How I can make this match?

**Comment by Ben-Ensembl** [comment]
Hi zhypan,

We're sorry for the delay in responding to your query. For your future reference, technical questions like these should be directed to the Ensembl Helpdesk: https://www.ensembl.org/Help/Contact

However, the hg38.chrom.sizes files from UCSC will always differ from the Ensembl records, if only because UCSC and Ensembl use different chromosome notations within their files. To work with the Ensembl GTF files, we advise creating a chrom sizes file from the Ensembl databases.

If you have any further questions, please do contact the Ensembl Helpdesk with your original question and follow up questions and we'll do our best to help you from there.

Best wishes

Ben
